# Site settings
title: Code for Good
description: "A minimal blog template, build with Jekyll."
url: "http://www.codeforgood.co/"
author:
  name: "Georgia Davis"
  email: "contact@codeforgood.co"
  url: "http://www.georgiatdavis.com/code-for-good-curriculum/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
